import type { NextPage } from "next";
import Head from "next/head";

import NavBar from "../sections/Nav-Bar/NavBar";
import FirstSection from "../sections/FirstSection.tsx/FirstSection";
import SecondSection from "../sections/Second Section/SecondSection";
import ThirdSection from "../sections/Third section/ThirdSection";
import FourthSection from "../sections/Fourth Section/FourthSection";
import FifthSection from "../sections/Fifth Section/FifthSection";
import Video from "../sections/Video Section/Video";
import Newsletter from "../sections/Newsletter Section/Newsletter";
import Blogs from "../sections/Blogs/Blogs";
import Photo from "../sections/PhotoGallery/Photo";

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false; /* eslint-disable import/first */

const Home: NextPage = () => {
   return (
      <>
         <Head>
            <title>Resturant</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <NavBar />
         <FirstSection />
         <SecondSection />
         <ThirdSection />
         <FourthSection />
         <FifthSection />
         {/* <Video /> */}
         <Blogs />
         <Photo />
         <Newsletter />
      </>
   );
};

export default Home;
